### ISSUE TITLE
Error downloading CE version of saiku plugin for Pentaho

### ISSUE THREAD

**Issue by virivigio** [pentaho/marketplace-metadata#695]
Hi, the saiku plugin installation stopped working, I don't know who's in charge of notifying URL for components but actually this thread explain the error.
https://community.hitachivantara.com/thread/15031-how-to-add-saiku-analytics-plugin-in-pentaho-bi-server-81-error-in-installing-plugin
Please fix it otherwise it will be a barried to community version adoption
Regards
Virgilio

**Comment by buggtb** [comment]
No new pentaho releases but saiku is back up and running at saiku.bi for standalone deployments
